[package]
name = "sikri_client"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[test]]
name = "e2e_client"
path = "tests/e2e/e2e_client.rs"


[dependencies]
lib-schemas = { git = "https://github.com/Mattilsynet/landdyrtilsyn-libs.git" }
reqwest = {version = "0.12.23", features = ["json"] }
serde = {version = "1.0.228", features = ["derive"]}
tokio = {version = "1.47.1", features = ["full"]}
chrono = { version = "0.4.42", features = ["serde"] }
anyhow = { version = "1.0.100" }
gcp_auth = { version = "0.12.6" }
base64 = "0.22.1"




