[workspace]
members = [
  "crates/app",
  "crates/domain",
  "crates/application",
  "crates/infrastructure",
  "crates/read_worker",
  "crates/health_check",
]
resolver = "2"

# optional: apply lints to all members
[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
enum_glob_use = "deny"


