[package]
name = "skuffen"
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace]
members = [
  ".",
  "src/domain",
  "src/application",
  "src/infrastructure",
  "crates/sikri_client",
  "integration-tests"
]
resolver = "2"

[[bin]]
name = "skuffen"
path = "src/main.rs"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
enum_glob_use = "deny"


[dependencies]
domain        = { path = "src/domain" }
application   = { path = "src/application" }
infrastructure = { path = "src/infrastructure" }
lib-schemas = { git = "https://github.com/Mattilsynet/landdyrtilsyn-libs.git", features = ["skuffen"] }
lib-nats = { git = "https://github.com/Mattilsynet/landdyrtilsyn-libs.git", package = "lib-nats" }
dotenvy = "0.15.7"
anyhow = "1.0.100"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.89"

serde = { version = "1", features = ["derive"] }
thiserror = "2.0.16"
