[package]
name = "skuffen"
version = "0.1.0"
edition = "2021"
rust-version = "1.91"
license = "MIT"

[workspace]
members = [
  ".",
  "src/domain",
  "src/application",
  "src/infrastructure",
  "crates/sikri_client",
  "crates/adr-fmt",
  "integration-tests"
]
resolver = "2"

[[bin]]
name = "skuffen"
path = "src/main.rs"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
enum_glob_use = "deny"

[dependencies]
domain        = { path = "src/domain" }
application   = { path = "src/application" }
infrastructure = { path = "src/infrastructure" }
lib-schemas = { git = "https://github.com/Mattilsynet/landdyrtilsyn-libs.git", package = "lib-schemas", features = ["skuffen"] }
lib-nats = { git = "https://github.com/Mattilsynet/landdyrtilsyn-libs.git", package = "lib-nats" }
dotenvy = "0.15.7"
anyhow = "1.0.102"
tokio = { version = "1.52.2", features = ["full"] }
async-trait = "0.1.89"
tracing = "0.1.44"

serde = { version = "1.0.228", features = ["derive"] }
rustls = { version = "0.23.38", features = ["aws_lc_rs"] }
thiserror = "2.0.18"

# CVC
aws-lc-sys = "0.40.0"
aws-lc-rs = "1.16.3"
