
[package]
name = "domain"
version = "0.1.0"
edition = "2021"


[dependencies]
lib-schemas = { git = "https://github.com/Mattilsynet/landdyrtilsyn-libs.git", rev = "91e69423239d3e6b496506e9e48699a26896124e", features = ["skuffen"] }
uuid = { version = "1.23.1", features = ["serde", "v7", "v5", "v4"] }
chrono = { version = "0.4.44", features = ["serde"] }
anyhow = "1.0.102"
thiserror = "2.0.18"
