[package]
name = "skuffen-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
application = { path = "../src/application" }
infrastructure = { path = "../src/infrastructure" }
domain = { path = "../src/domain" }
lib-schemas = { git = "https://github.com/Mattilsynet/landdyrtilsyn-libs.git", features = ["skuffen"] }
lib-nats = { git = "https://github.com/Mattilsynet/landdyrtilsyn-libs.git", package = "lib-nats" }

anyhow = "1"
async-nats = "0.46.0"
bytes = "1"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.6", default-features = false, features = [
  "postgres",
  "runtime-tokio-native-tls",
  "uuid",
  "chrono",
  "migrate",
] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
uuid = { version = "1", features = ["serde", "v4", "v7"] }

async-trait = "0.1"
testcontainers = "0.16"
testcontainers-modules = { version = "0.8", features = ["postgres"] }

[dev-dependencies]
tracing = "0.1"
