[package]
name = "skuffen-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
skuffen = { workspace = true }
application = { workspace = true }
infrastructure = { workspace = true }
domain = { workspace = true }
lib-schemas = { workspace = true, features = ["skuffen"] }
lib-nats = { workspace = true }

anyhow = { workspace = true }
async-nats = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
uuid = { workspace = true, features = ["serde", "v4", "v7"] }
rustls = { workspace = true, features = ["aws_lc_rs"] }
dotenvy = { workspace = true }

testcontainers = { workspace = true }
testcontainers-modules = { workspace = true, features = ["postgres"] }

[dev-dependencies]
tracing = { workspace = true }

# CVC
aws-lc-sys = { workspace = true }
aws-lc-rs = { workspace = true }
